### ISSUE TITLE
UI application crash on adding User Profile link

### ISSUE THREAD

**Issue by yogeshpaliyal** [EddieHubCommunity/RepoRater#10]
### Description

When assing a user profile link in add review eg:
https://github.com/yogeshpaliyal the app crash.

### Screenshots

![Screenshot_2023-12-22-16-16-22-308_com android chrome](https://github.com/EddieHubCommunity/RepoRater/assets/9381846/03c57ab9-cb0a-4d32-993b-35428c8618f8)

**Comment by Shoetan** [comment]
I am trying to recreate this bug not have not been able to @yogeshpaliyal

**Comment by yogeshpaliyal** [comment]
Add user profile link here
https://repo-rater.eddiehub.io/rate

**Comment by eddiejaoude** [comment]
Thank you for raising. This is not specific to user profiles but any url that is not a valid repo. I will close this issue as we have a similar one that has progressed further https://github.com/EddieHubCommunity/RepoRater/issues/48
