### ISSUE TITLE
[BUG] Text elements on the homepage are not visible

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/RepoRater#104]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production

### Description

Text elements on the homepage like language and star count are not visible due to the colour scheme

### Steps to Reproduce

Visit the homepage and you will able to notice it.

### Screenshots

<img width="1478" alt="Screenshot 2024-01-08 at 1 26 27 PM" src="https://github.com/EddieHubCommunity/RepoRater/assets/51878265/f0b16b8d-f1f3-495b-9b5f-ae2fb69462f7">

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
Thanks Pradumna. My home page looks different 🤔 

<img width="1670" alt="Screenshot 2024-01-08 at 09 32 49" src="https://github.com/EddieHubCommunity/RepoRater/assets/624760/400a5ac2-ad7b-4fa5-a3b3-41c0137e1310">

**Comment by Vijaykv5** [comment]
<img width="1429" alt="Screenshot 2024-01-08 at 3 43 14 PM" src="https://github.com/EddieHubCommunity/RepoRater/assets/94985341/d3120a0e-6337-46b5-b0b2-b6275d9e4dd1">
Its not visible from my side @eddiejaoude. 
May I can work on this issue?

**Comment by eddiejaoude** [comment]
Thanks for testing @Vijaykv5 , sure I have assigned it to you 👍

**Comment by Vijaykv5** [comment]
idk but now it has fixed in production @eddiejaoude

**Comment by Pradumnasaraf** [comment]
> Thanks Pradumna. My home page looks different 🤔
> 
> <img alt="Screenshot 2024-01-08 at 09 32 49" width="1670" src="https://private-user-images.githubusercontent.com/624760/294858655-400a5ac2-ad7b-4fa5-a3b3-41c0137e1310.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ3ODI4NjgsIm5iZiI6MTcwNDc4MjU2OCwicGF0aCI6Ii82MjQ3NjAvMjk0ODU4NjU1LTQwMGE1YWMyLWFkN2ItNGZhNS1hM2IzLTQxYzAxMzdlMTMxMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwOVQwNjQyNDhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ODZmNDdlZTlhMGI0NWU1YTA1NDE2M2VmYTFmOGRkMTcyYzUwNmNjZTMxYmU3NTFlM2MzZDhhMmE3NDM5M2UyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.9-9eGsYkFndVu7a1cH82mAeWC5z4Z3T00JqKcPeAVBc">

That's weird that is working fine on your side 🤔. I am testing in chorme

**Comment by Pradumnasaraf** [comment]
> Thanks Pradumna. My home page looks different 🤔
>

That's weird that is working fine on your side 🤔, @eddiejaoude. I am testing in Chorme

**Comment by eddiejaoude** [comment]
@Pradumnasaraf can you retest in production with your setup?

**Comment by Vijaykv5** [comment]
Earlier when I've checked in website, it worked fine.
But right now it's not working.
Issue with production?? @eddiejaoude 
<img width="1323" alt="Screenshot 2024-01-12 at 1 09 25 PM" src="https://github.com/EddieHubCommunity/RepoRater/assets/94985341/b83c87f7-77c6-4695-b005-6607122ece03">

**Comment by ArvindParekh** [comment]
Worked fine for me on Chrome, but breaks on Firefox. Tested it using dev tools and just toggling the dark mode fixes it. 

https://github.com/EddieHubCommunity/RepoRater/assets/71211731/5397575d-aceb-4a64-bd30-5b3df4e89f10

Chrome and Firefox has a `prefers-color-scheme` feature. This feature allows web content to adapt to the user's preferred color scheme, such as light or dark mode. So maybe, people that use light mode in their browser and use repo-rater in dark mode may see this issue, I guess?

**Comment by Pradumnasaraf** [comment]
Same issue @eddiejaoude 
![Uploading Screenshot 2024-01-14 at 9.48.59 AM.png…]()

**Comment by eddiejaoude** [comment]
Ah yes, something we need to fix then 👍  thank you everyone

**Comment by WaqarTabish2807** [comment]
![image](https://github.com/EddieHubCommunity/RepoRater/assets/85379681/a1ff25be-140b-4594-84ff-bbbdcf6dabe0)

![image](https://github.com/EddieHubCommunity/RepoRater/assets/85379681/978c01d2-231c-4d0d-9df9-734eb3a0a3eb)

Works fine in both chrome and brave.

**Comment by eddiejaoude** [comment]
> Works fine in both chrome and brave.

Thank you WaqarTabish2807 for testing, we should change it just to be sure

**Comment by GaganpreetKaurKalsi** [comment]
The elements are missing color class `text-gray-400` 
(I added the class for KinsonDigital/Velaptor)

<img width="959" alt="image" src="https://github.com/EddieHubCommunity/RepoRater/assets/54144759/57c9ade2-6d6a-4bec-b1fd-87964bba31d6">


<br><br>
I can work on this issue if nobody is currently looking at this.

**Comment by Vijaykv5** [comment]
You can go ahead @GaganpreetKaurKalsi

**Comment by eddiejaoude** [comment]
thank you all! 👍  @GaganpreetKaurKalsi I have assigned it to you
