### ISSUE TITLE
[BUG] Blurry profile picture

### ISSUE THREAD

**Issue by Pradumnasaraf** [EddieHubCommunity/RepoRater#105]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production

### Description

The profile picture on the bottom left corner is blurry and not clear to understand

### Steps to Reproduce

Visit the homepage and you will able to notice it.

### Screenshots

<img width="654" alt="Screenshot 2024-01-08 at 1 30 13 PM" src="https://github.com/EddieHubCommunity/RepoRater/assets/51878265/dca434fb-5b5b-4117-8f75-66ca9b52091d">

### Do you want to work on this issue?

No

**Comment by Vijaykv5** [comment]
I would love to work on this issue :)

**Comment by eddiejaoude** [comment]
Thank you Pradumna!

Sorry @Vijaykv5 I already fixed this when it was mentioned in Discord.
