### ISSUE TITLE
[BUG] Github icon not visible in Sidebar Footer when not logged in

### ISSUE THREAD

**Issue by vneogi199** [EddieHubCommunity/RepoRater#107]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Description

When user is not logged in, in the sidebar footer the Github icon is not clearly visible

![image](https://github.com/EddieHubCommunity/RepoRater/assets/20491952/5452bbca-0a7f-4f91-b5f4-de90c600b514)

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Open incognito tab so that you are not in logged in state
2. Go to homepage
3. Open sidebar if not open
4. Look at sidebar footer near login text, github icon is not clearly visible

### Screenshots

![image](https://github.com/EddieHubCommunity/RepoRater/assets/20491952/8c91844d-5caa-4201-a00a-60121b97448a)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Change background color of <Link> to bg-gray-500 and hover:bg-gray-400.

After change without login:
![image](https://github.com/EddieHubCommunity/RepoRater/assets/20491952/45a17e9e-e214-4608-abbd-60b0eaf39340)

After change with login:
![image](https://github.com/EddieHubCommunity/RepoRater/assets/20491952/b7954add-539f-405f-b4c0-d6b65b2c0c40)

**Comment by eddiejaoude** [comment]
thank you for raising the issue 👍 

- please make it visible by changing the GitHub icon to white, and not the background colour
