### ISSUE TITLE
Add Meta Tags for Enhanced SEO⭐

### ISSUE THREAD

**Issue by Nishitbaria** [EddieHubCommunity/RepoRater#109]
**I've noticed that our web pages are missing essential meta tags which play a crucial role in optimizing our site for search engines. Implementing these tags will help improve our project's SEO, making it more discoverable and accessible to users via search engines.**

Difference 

![image](https://github.com/EddieHubCommunity/RepoRater/assets/85815172/0f5215a4-f88b-4d8a-8ace-acb0d2b0bc2e)

Refence Link  : https://nextjs.org/docs/app/building-your-application/optimizing/metadata

**Expected Benefits:**
- Enhanced search engine ranking, making our site more discoverable to users.
- Improved visibility and presentation on social media platforms, leading to better user engagement.
- Increased traffic through more effective and targeted SEO strategies.

**Comment by eddiejaoude** [comment]
Issue template was not used?

Please be specific, what tags?
