### ISSUE TITLE
[FEATURE] UI Improvement - standard card sizing

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/RepoRater#11]
### Description

Currently the cards/rows are different sizes. This would be more visually appealing and easier to navigate visually if the sizing is standardized

### Screenshots

![card-inconsistency](https://github.com/EddieHubCommunity/RepoRater/assets/97615019/8fb802fb-6343-4723-9c6c-5c7729517fda)

**Comment by eddiejaoude** [comment]
We have redesigned the app, and I think this is now resolved, so I will close this issue, please have a look at the new design and raise any new relevant issues
