### ISSUE TITLE
[BUG] Overflowing screen on the mobile view

### ISSUE THREAD

**Issue by vatsalsinghkv** [EddieHubCommunity/RepoRater#112]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production

### Description

I've noticed the web-app has some overflow issue in the mobile view which breaks the responsiveness of the app.
- Repositories names overflow.
- Rating component break the flow in the repository card.

### Steps to Reproduce

1. Go to [home page](https://repo-rater.eddiehub.io/).
1. Open the mobile view.
1. Repositories names are overflowing, results in breaking navbar.

### Overflow Issue
<img width="372" alt="Screenshot 2024-01-09 at 2 54 32 PM" src="https://github.com/EddieHubCommunity/RepoRater/assets/68834718/a8b40729-9ce1-49d1-bd59-0c0edf522513">

### Rate component breaks the flow on mobile view
<img width="353" alt="Screenshot 2024-01-09 at 2 58 48 PM" src="https://github.com/EddieHubCommunity/RepoRater/assets/68834718/e7597a02-d5d5-472d-9691-3f453c4399e5">

### Do you want to work on this issue?

Yes

#### 1. I can simply put the overflowing repository title in the next line in the repository card like this (I personally recommend this):
<img width="357" alt="Screenshot 2024-01-09 at 5 58 50 PM" src="https://github.com/EddieHubCommunity/RepoRater/assets/68834718/9f7e0ca1-3d18-4a70-a5f2-a8e1379d92cc">

#### 2. I can terminate the overflowing string and show *...* in the end of the repo name, and full repo name when you hover over it, like this:
<img width="368" alt="Screenshot 2024-01-09 at 6 05 27 PM" src="https://github.com/EddieHubCommunity/RepoRater/assets/68834718/72d1102a-1cb4-47b7-add6-df0aae745ada">

**Comment by eddiejaoude** [comment]
Thank you for raising, I have assigned it to you

**Comment by adityaraute** [comment]
@vatsalsinghkv Any update on this issue?

**Comment by vatsalsinghkv** [comment]
@adityaraute uh sorry I just lost track of time, yea fixed the issue but forgot to pushed it.

**Comment by adityaraute** [comment]
@vatsalsinghkv Do link the PR after pushing the code
