### ISSUE TITLE
[FEATURE] Add title metadata to each page

### ISSUE THREAD

**Issue by benaissazaki** [EddieHubCommunity/RepoRater#117]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Currently, pages have no title attribute, so only the url is is displayed in the browser tab.

### Proposed Solution

Add a title tag to each page:
- Home: `RepoRater: Rate GitHub Repos for Developer Experience`
- User Rankings: `User Rankings -RepoRater`
- Popular Repos: `Popular Repos -RepoRater`

### Screenshots

Browser tab before:
![image](https://github.com/EddieHubCommunity/RepoRater/assets/33980130/e868dcf6-e094-43c4-ada0-d450e00712cb)

Browser tab after:
![image](https://github.com/EddieHubCommunity/RepoRater/assets/33980130/f3c35a01-2c1d-4fe5-a94f-cd129668bad9)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

By exporting from the pages the metadata object as specified in the [NextJS docs.](https://nextjs.org/docs/app/building-your-application/optimizing/metadata)

For the client rendered pages (like /popular), I will create for them a layout whose sole purpose is to export that metadata object, since it cannot be used with `use client`.

**Comment by eddiejaoude** [comment]
Thank you 👍 I have assigned it to you
