### ISSUE TITLE
[FEATURE] UI Improvement - Repo Name

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/RepoRater#12]
### Description

Currently when multiple repos from the same base community are rated, it appears that there are duplicates. This is due to the repo logo being the most prominent visual item. 

Making the name of the repo more prominent by size and/or location may help solve this issue

### Screenshots

![repo-prominence-example](https://github.com/EddieHubCommunity/RepoRater/assets/97615019/de917648-b89a-495b-87cf-cb47d3eeb39c)

**Comment by eddiejaoude** [comment]
We have redesigned the app, and I think this is now resolved, so I will close this issue, please have a look at the new design and raise any new relevant issues
