### ISSUE TITLE
[FEATURE] add social icons to website

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/RepoRater#122]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Contributors might wonder where they can connect with EddieHub outside of GitHub.

### Proposed Solution

Adding social icons(YouTube, Discord, X  etc) would help.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

I plan on adding these icons to the sidebar on the website or create a footer like the one on BioDrop:
![inspiration](https://github.com/EddieHubCommunity/RepoRater/assets/105683440/225e589f-c994-466d-8355-32b29fe74f4e)

**Comment by Bashamega** [comment]
Hello:)

I think adding socials to the website will not be a good idea, since the majority of the community is on GitHub.

**Comment by eddiejaoude** [comment]
I think in the past we have used my social handles, which is not the best. I will close this for now.

Thank you both for the collaboration
