### ISSUE TITLE
[FEATURE] Select from existing repos to rate

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/RepoRater#13]
### Description

Currently you have to add a repo url to rate it, a feature for consideration is to be able to choose from repos that have already been rated OR add a new repo via url.

https://repo-rater.eddiehub.io/rate

### Screenshots

![add-a-rating](https://github.com/EddieHubCommunity/RepoRater/assets/97615019/d1e0ab1f-0108-4561-b546-78bc785012da)

**Comment by rohan-kulkarni-25** [comment]
Hey @amandamartin-dev! I am not sure are we trying to fix same issue or not. I guess we do but in different ways. 

Request that maintainers please have a look at this issue and #43

**Comment by amandamartin-dev** [comment]
> Hey @amandamartin-dev! I am not sure are we trying to fix same issue or not. I guess we do but in different ways.
> 
> Request that maintainers please have a look at this issue and #43

Thanks for noticing this! This issue is to create a dropdown for adding issues so it appears to be different functionality from what I am seeing.  Will leave it for now.

**Comment by eddiejaoude** [comment]
I think they are different, thanks for checking though 👍 

@amandamartin-dev we can now click on the repo's card and it goes directly to this rating page with the url prefilled - is this what you mean?

**Comment by amandamartin-dev** [comment]
@eddiejaoude that works perfectly. I'll close this issue

**Comment by eddiejaoude** [comment]
Thanks Amanda 👍  I think we need to make it more obvious as now it is a bit hidden, but the functionality is there
