### ISSUE TITLE
[BUG] Star rating colours can be confusing

### ISSUE THREAD

**Issue by adityaraute** [EddieHubCommunity/RepoRater#134]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Description

Upon trying to rate a repo, I noticed that the stars were coloured green, and the last star was actually coloured blue. If I changed the rating to 4 stars, the first 3 stars appear green, 4th one appears blue, and the 5th one appears black. 
This leads to some confusion.

I suggest we colour all selected stars as golden `#FFD700`, and unselected stars can remain black or grey.
Then there will also not be any need to add a number in parantheses after the stars. (See the screenshot for clarity)

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Go to Add Rating page
1. Play around with the star ratings
1. Notice that the UX is not the most straightforward

### Screenshots

![image](https://github.com/EddieHubCommunity/RepoRater/assets/43912470/4f6d2ede-bb95-432b-9285-4bf943f78875)

### Do you want to work on this issue?

No

### If "yes" to above, please explain how you would technically implement this

NA

**Comment by Bashamega** [comment]
@eddiejaoude Hello:)
I would like to work on this issue

**Comment by eddiejaoude** [comment]
Thanks for raising @adityaraute and thank you @Bashamega, i will assign it to you 👍
