### ISSUE TITLE
[FEATURE] Remove `Github /` from User Rankings

### ISSUE THREAD

**Issue by adityaraute** [EddieHubCommunity/RepoRater#135]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

After navigating to the User Rankings we notice that all users have a prefix `GitHub /` 
Since we are using GitHub OAuth, all users will have this title. 
I don't see the point of having the same prefix for all users. It would make for a much cleaner UI if this prefix is omitted.

### Proposed Solution

When displaying that part of the card, we can simply truncate that part of the string, and display just the username, as is done in the Activity feed. (See screenshot below)

### Screenshots

User Rankings page:
![image](https://github.com/EddieHubCommunity/RepoRater/assets/43912470/89c66551-a3ff-4435-b75f-f12bed2a3e8d)

Activity Feed
![image](https://github.com/EddieHubCommunity/RepoRater/assets/43912470/ea47b361-d65c-4d24-95ea-5325bcd07e52)

### Do you want to work on this issue?

No

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

NA

**Comment by Bashamega** [comment]
I would like to work on that.
There is a line that i just need to get rid of

**Comment by eddiejaoude** [comment]
Thank you for raising the issue. I would like to keep the prepended `github`, this was done as part of the design, because in the future we may have other sign in options. So i will close this issue for now
