### ISSUE TITLE
[BUG] User rating not displaying after success

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/RepoRater#14]
### Description

I added a rating for BioDrop
Long lag  - enough that I thought it didn't work
Recieved success message
clicked user ratings
did not see my rating
checked list ratings
biodrop ratings count has not increased

No console errors so this may be difficult to debug

**Comment by eddiejaoude** [comment]
Thanks Amanda, I think this has now been resolved with the new design / rewrite
