### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by amanr-dev** [EddieHubCommunity/RepoRater#146]
The RepoRater badge in the README.md file is not showing.

## Screenshot
![Screenshot 2024-07-28 123330](https://github.com/user-attachments/assets/7f71378a-0b19-438d-8fdd-90a1c7728add)

**Comment by eddiejaoude** [comment]
Thank you for raising the issue

**Comment by Bashamega** [comment]
I would like to work on this

**Comment by eddiejaoude** [comment]
sure, assigned to you @Bashamega 👍  - this was working before, so not sure why it broke, I am super curious though

**Comment by Bashamega** [comment]
@eddiejaoude For some reason this issue wasn't closed. Can you close it?

**Comment by eddiejaoude** [comment]
oh strange, thank you 👍
