### ISSUE TITLE
[BUG] Add a button to install the browser extension on the website

### ISSUE THREAD

**Issue by Bashamega** [EddieHubCommunity/RepoRater#147]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Description

There is no button that can tell the user to download the browser extension.

### Steps to Reproduce

Open the website and try to find a link for the extension

### Screenshots

![image](https://github.com/user-attachments/assets/c5becbd8-a552-424b-b4ab-08e3da076ce4)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I will add a get browser extension button on the side bar

**Comment by eddiejaoude** [comment]
Thank you for raising 👍  I have assigned it to you @Bashamega
