### ISSUE TITLE
[FEATURE] UI Improvement - duplicate links to repo

### ISSUE THREAD

**Issue by amandamartin-dev** [EddieHubCommunity/RepoRater#15]
### Description

Currently each card has 2 links to the repo. This is not necessary and given the small amount of space in each card removing this could create more visual whitespace which may be more appealing

Reccomend removing the Github with a link symbol as the linked repo title is more descriptive

Alternate idea would be to update the "Github" label to have the name of the repo and removing the lower link.

### Screenshots

![duplicate links](https://github.com/EddieHubCommunity/RepoRater/assets/97615019/10c067e8-0149-479c-b0bc-b7b81a18be64)

**Comment by aqsaaqeel** [comment]
I think one link at the bottom works better.

**Comment by eddiejaoude** [comment]
We have redesigned the app, so I will close this issue, please have a look at the new design and raise any new relevant issues
