### ISSUE TITLE
[FEATURE] Ability to switch between themes

### ISSUE THREAD

**Issue by ChinmayMhatre** [EddieHubCommunity/RepoRater#17]
### Description

Currently both light mode and dark mode themes are present but no button to toggle between them. A simple switch button would be great

### Screenshots

<img width="1428" alt="image" src="https://github.com/EddieHubCommunity/RepoRater/assets/51131670/708ddf93-b3aa-42a5-a795-b0e0335024a3">
<img width="1428" alt="image" src="https://github.com/EddieHubCommunity/RepoRater/assets/51131670/31dc8930-cb35-4320-a286-98c6c7d159f1">

**Comment by vinaybhamre** [comment]
@ChinmayMhatre Please assign this to me, I would like to work on this

**Comment by eddiejaoude** [comment]
> Currently both light mode and dark mode themes are present but no button to toggle between them. A simple switch button would be great

@ChinmayMhatre is this functionality already built into DaisyUI and we just need to add a toggle?

**Comment by ChinmayMhatre** [comment]
> > Currently both light mode and dark mode themes are present but no button to toggle between them. A simple switch button would be great
> 
> @ChinmayMhatre is this functionality already built into DaisyUI and we just need to add a toggle?

@eddiejaoude I found two solutions to this 

https://stackoverflow.com/questions/72926946/how-can-i-change-themes-using-daisyui-and-tailwindcss-in-a-react-project

The top answer suggests an approach without using any external package.
We can add some additional code to store the current theme to local storage. (seems like the better approach.)

alternatively the daisy ui docs also suggest using this package https://github.com/saadeghi/theme-change
(Added this just in case the earlier approach has any issues.)

**Comment by Hicode-dev** [comment]
> > > Currently both light mode and dark mode themes are present but no button to toggle between them. A simple switch button would be great
> > 
> > 
> > @ChinmayMhatre is this functionality already built into DaisyUI and we just need to add a toggle?
> 
> @eddiejaoude I found two solutions to this
> 
> The top answer suggests an approach without using any external package. We can add some additional code to store the current theme to local storage. (seems like the better approach.) https://stackoverflow.com/questions/72926946/how-can-i-change-themes-using-daisyui-and-tailwindcss-in-a-react-project
> 
> alternatively the daisy ui docs also suggest using this package https://github.com/saadeghi/theme-change (Added this just in case the earlier approach has any issues.)

buh you know  if you'd be using that tailwind as a special property for the  themes   you can use tailwind + dauisy UI  which is a great combo or you  use  local storage  that you talked about tho  the 2 works fine

**Comment by eddiejaoude** [comment]
I think for the moment, let's keep with a single theme in the new design, so I will close for now
