### ISSUE TITLE
[FEATURE] Show a spinner or system status when rating a repo

### ISSUE THREAD

**Issue by loftwah** [EddieHubCommunity/RepoRater#18]
### Description

When a user rates a repository, there is no immediate indication of the process being initiated or in progress. This lack of feedback can be confusing, especially since the operation can take up to 20 seconds to complete.

### Issue
According to the Nielsen Norman Group's usability heuristics, visibility of system status is fundamental. Users should be informed about what is going on through appropriate feedback within a reasonable time. Currently, after a user inputs a repository URL and clicks the "Rate" button, there is no visual cue or progress indicator until the process completes successfully. This can lead to uncertainty or repeated button presses, assuming the initial attempt did not register.

### Expected Behavior
After clicking the "Rate" button, some form of feedback should be immediately presented to the user. This could be in the form of a loading spinner, progress bar, or a simple text update changing the button text to "Rating in progress..."

### Proposed Solution
Implement an immediate visual response upon initiating the rating process. Possibilities include:

- A loading spinner replacing the button or appearing next to it.
- Disabling the button and changing its text to indicate that the rating is being processed.
- A progress bar that fills up as the operation progresses.
- An informative tooltip or message box that pops up when the process takes longer than a few seconds.

### Additional Context
This improvement would align the application with widely accepted UX principles and greatly enhance the user experience by providing constant and clear feedback throughout the rating process.

### Screenshots

![chrome_WWmMIc1H7N](https://github.com/EddieHubCommunity/RepoRater/assets/19922556/d27253e5-96fe-4b92-aa64-9d1c9dfc1bcb)

**Comment by eddiejaoude** [comment]
Thank you Dean! I have now added this feature with 3 bouncing dots  https://github.com/EddieHubCommunity/RepoRater/commit/9fa17176675f3eb2103bc83583c7e2d0a7cf1fc5

<img width="1680" alt="Screenshot 2023-12-23 at 15 26 30" src="https://github.com/EddieHubCommunity/RepoRater/assets/624760/08fac884-7768-49c8-a134-0fbe8ad0b29e">
