### ISSUE TITLE
Total Stars is misleading

### ISSUE THREAD

**Issue by xkrishguptaa** [EddieHubCommunity/RepoRater#2]
### Description

<img width="257" alt="image" src="https://github.com/EddieHubCommunity/RepoRater/assets/135469703/110e3908-7d63-42f1-b5a5-90c1361c0706">

Total stars is misleading, it is meant to be a rating I believe

**Comment by eddiejaoude** [comment]
Good point, thank you 👍

**Comment by eddiejaoude** [comment]
<img width="301" alt="Screenshot 2023-12-21 at 08 34 56" src="https://github.com/EddieHubCommunity/RepoRater/assets/624760/4993e09f-65d0-4835-9991-659f4abb6afa">
