### ISSUE TITLE
Name/Logo in Navbar to navigate to the list ratings page

### ISSUE THREAD

**Issue by divyanshraj0408** [EddieHubCommunity/RepoRater#27]
### Description

We should be redirected to the List Rating page after clicking the "GitHub Repo Rater" (The logo) if we are on any other page.

### Additional information

I think this can be discussed as well but it is a very common practice for most websites.

**Comment by divyanshraj0408** [comment]
i think i will be working on this.

**Comment by eddiejaoude** [comment]
PR merged
