### ISSUE TITLE
There should be a way to open the repo

### ISSUE THREAD

**Issue by xkrishguptaa** [EddieHubCommunity/RepoRater#3]
### Description

<img width="270" alt="image" src="https://github.com/EddieHubCommunity/RepoRater/assets/135469703/9dc12118-c4d8-419d-92b3-25f5320eabd0">

I think there should be one way to click and read the repository

**Comment by eddiejaoude** [comment]
You can by clicking on the text `GitHub` but it is not clear, so we need to improve that 💯

**Comment by thevinitgupta** [comment]
Instead of the text `GitHub`, we can have an icon on the top right which opens the repo

**Comment by eddiejaoude** [comment]
Yep 👍 I have just added that, thanks for the suggestion! I also added a link and icon to the repo name at the bottom of the card...

<img width="263" alt="Screenshot 2023-12-21 at 10 40 44" src="https://github.com/EddieHubCommunity/RepoRater/assets/624760/91aa664f-b0cd-4f6f-aac2-5aa16c108432">
