### ISSUE TITLE
[Bug]: The rating page is broken when refresh the page.

### ISSUE THREAD

**Issue by Himanshuch8055** [EddieHubCommunity/RepoRater#35]
### Description

"When I refresh the rating page, it doesn't work properly."

### Screenshots

![image](https://github.com/EddieHubCommunity/RepoRater/assets/94627200/5433f574-1201-451f-9726-2875eafbb12d)

**Comment by eddiejaoude** [comment]
Thank you 👍 fixed here https://github.com/EddieHubCommunity/RepoRater/commit/82d03715b0c4311833c469257852d14e511e87ac
