### ISSUE TITLE
[DOCS] Contributing Guide needed

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/RepoRater#36]
### Description

People might want to know how to effectively contribute to this project, so a guide is needed.

**Comment by MuthoniMN** [comment]
Hey @eddiejaoude, I would love to work on this issue. Could you please assign it to me?

**Comment by eddiejaoude** [comment]
I have added a contribution guide from BioDrop, and others have updated the quickstart guide. I will close for now and please review, further specific issues can be raise
