### ISSUE TITLE
[FEATURE] Search bar

### ISSUE THREAD

**Issue by schmelto** [EddieHubCommunity/RepoRater#40]
### Description

Add a search bar for searching for specific projects

**Comment by ctrl07** [comment]
Hello Schmelto,

Please can you tell me if this is a good resource for this enhancement? 

https://nextjs.org/learn/dashboard-app/adding-search-and-pagination

**Comment by SaiDevaHarshaR** [comment]
Please assign the issue to me, I will give it a shot.

**Comment by eddiejaoude** [comment]
Thank you for raising 👍 , we just deployed a redesign, I think this now has a search bar
