### ISSUE TITLE
[BUG] Nav bar overflowing

### ISSUE THREAD

**Issue by yogeshpaliyal** [EddieHubCommunity/RepoRater#41]
### Description
Navigation bar is overflowing horizontally and making site horizontally scrollable.

### Screenshots
![Screenshot_2023-12-25-20-30-41-939_com android chrome](https://github.com/EddieHubCommunity/RepoRater/assets/9381846/1e7676a2-2bc6-4e5a-9a9c-ac1bde92ab63)

**Comment by sohanpaliyal** [comment]
I want to fix this issue.please assign this to me

**Comment by eddiejaoude** [comment]
> I want to fix this issue.please assign this to me

assigned to you
