### ISSUE TITLE
[BUG] Navbar isn't responsive

### ISSUE THREAD

**Issue by vatsalsinghkv** [EddieHubCommunity/RepoRater#45]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production

### Description

When we open the website on the mobile device navbar overflows the device's width.

### Steps to Reproduce

1. Go to https://repo-rater.eddiehub.io/ page.
2. Open the website in mobile view or open in a mobile device.
3. Check the navbar.

### Screenshots

<img width="441" alt="Screenshot 2023-12-26 at 5 19 44 PM" src="https://github.com/EddieHubCommunity/RepoRater/assets/68834718/f36aa17d-4376-4031-947c-e8b058dd2bf7">
<img width="468" alt="Screenshot 2023-12-26 at 5 20 03 PM" src="https://github.com/EddieHubCommunity/RepoRater/assets/68834718/2628514d-30c8-4000-bc5e-fab3ad794393">

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I'd probably fix the responsiveness of the navbar by inspecting the navbar, and fix the flexbox by changing it's  flex direction on relevant breakpoints

**Comment by ChinmayMhatre** [comment]
Hi Vatsal, thank you for raising the issue, It is already being worked on at #41
