### ISSUE TITLE
[BUG] App Crash on Invalid GitHub URL Input

### ISSUE THREAD

**Issue by Nithishvb** [EddieHubCommunity/RepoRater#48]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Description

App crashes when an invalid GitHub URL is entered in rating screen. 

### Steps to Reproduce

1.go to rating screen.
2. enter this url "https://github.com/" and submit.  

### Screenshots

![Screenshot 2023-12-27 221051](https://github.com/EddieHubCommunity/RepoRater/assets/83941930/8598bc52-ff65-4395-87ba-a28b880d9462)

### Do you want to work on this issue?

Yes

**Comment by eddiejaoude** [comment]
Thank you 👍  I will mark as ready for dev
