### ISSUE TITLE
[FEATURE]: users should be able to click on a repo to rate

### ISSUE THREAD

**Issue by Dun-sin** [EddieHubCommunity/RepoRater#5]
### Description

Right now we have to add a rating you have to click on add rating, but it should be easier.

Here's a possible solution:
- add a button called `rate this project`
- when click it sets the repo url and all the user need to do is add a rating

**Comment by naikmubashir** [comment]
Assign me this issue, I would like to work on it.

**Comment by eddiejaoude** [comment]
Thank you for the suggestion, this has now been done 👍
