### ISSUE TITLE
DOCS: add badge to README

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/RepoRater#51]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

There isn’t a badge on the README file.

### Proposed Solution

Add one.

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
Thank you, but this has already been completed in this repo

<img width="528" alt="Screenshot 2023-12-29 at 12 47 00" src="https://github.com/EddieHubCommunity/RepoRater/assets/624760/3b0b2165-7d67-4993-8497-4395840192e8">
