### ISSUE TITLE
[FEATURE] add GitHub Action

### ISSUE THREAD

**Issue by CBID2** [EddieHubCommunity/RepoRater#52]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Currently, repos are added manually. While good, this can make the voting process tedious 

### Proposed Solution

Add Krish’s GitHub action: https://github.com/marketplace/actions/repo-rater-action

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I'd just follow Krish's directions

**Comment by CBID2** [comment]
Great @eddiejaoude! :) I decided to work on this issue, so can you assign to me please? :)

**Comment by eddiejaoude** [comment]
Docs have been added to add this githb action to a repo. Sure I will assign to you
