### ISSUE TITLE
[FEATURE] Success alert disappear

### ISSUE THREAD

**Issue by amanr-dev** [EddieHubCommunity/RepoRater#56]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Once the user has provided a rating, the success alert should disappear automatically after a few seconds.

### Proposed Solution

Success alert should disappear after some seconds

### Screenshots

![Screenshot 2023-12-30 154643](https://github.com/EddieHubCommunity/RepoRater/assets/124811276/56c6634e-1997-4a6e-83b8-41436289e1fe)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I think the setTimeout function solve this.

**Comment by eddiejaoude** [comment]
This will be different in the new design, but the same issue will need to be resolved. Let me push my changes to the `dashboard` branch where you can make the changes

**Comment by amanr-dev** [comment]
> This will be different in the new design, but the same issue will need to be resolved. Let me push my changes to the `dashboard` branch where you can make the changes

So I need to work on the `dashboard` branch ?

**Comment by eddiejaoude** [comment]
The dashboard branch was just merged into prototype branch, so you can continue with the default branch with is current `prototype`

**Comment by amanr-dev** [comment]
> The dashboard branch was just merged into prototype branch, so you can continue with the default branch with is current `prototype`

OK and nice design👍

**Comment by eddiejaoude** [comment]
thank you 👍

**Comment by amanr-dev** [comment]
Hi @eddiejaoude , I tried to fix the issue in #89 . Can you please review the PR.

**Comment by eddiejaoude** [comment]
yes I got the PR notification
