### ISSUE TITLE
[FEATURE] add comments

### ISSUE THREAD

**Issue by Dun-sin** [EddieHubCommunity/RepoRater#6]
### Description

It would be great to provide more ways to review the project.

Here's a proposed solution:
- rating is to be compulsory
- an input box with questions like (comments on the maintainer's)
- user can optionally or compulsorily pick one question to answer before they can review

better questions can be asked,

**Comment by eddiejaoude** [comment]
This is a good idea, but with comments comes a lot more work, for example report post, then admin pages to manage any reported posts etc - so I will close for now as needs a lot of planning
