### ISSUE TITLE
[FEATURE] add `/project` and `/leaderboard` endpoints

### ISSUE THREAD

**Issue by xkrishguptaa** [EddieHubCommunity/RepoRater#60]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Add an endpoint for:

- [ ] A `/project/{owner}/{repo}` endpoint
- [ ] A `/leaderboard` endpoint

### Proposed Solution

-

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
I think issue should be separate in 2.

I created a PR for the leaderboard https://github.com/EddieHubCommunity/RepoRater/pull/65, so this PR could be for that. Then the project endpoint could be another issue
