### ISSUE TITLE
Repository feedback

### ISSUE THREAD

**Issue by dhruvabhat24** [EddieHubCommunity/RepoRater#63]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

You have a option of giving a rating for the repository. If there is any option providing a feedback for the repository. Suppose if a repository got 5 star the person need to know why he got 5 rates. And if a person got low rating then he/she need to know why they got less rating and on what field they need to work. 

### Proposed Solution

For this we can implement a mechanism where a user can submit with detiled feedback which will be stored in the Appwrite. And a dynamic dashboard using NextJs which displays summarized feedback for repository.

### Do you want to work on this issue?

Yes

### Feedback System for NextJS Repository Platform
**Technologies Used:**
- NextJS
+ Appwrite
+ DaisyUI (Tailwind)
+ Features:
+ Feedback Component:

+ Add a feedback component in NextJS to collect user ratings and detailed feedback.
+ Utilize DaisyUI for a visually appealing UI and integrate Tailwind CSS for styling.
+ Backend Setup (Appwrite):

+ Create an Appwrite collection to store feedback data, including ratings and comments.
+ Use Appwrite SDK in NextJS backend to interact with the Appwrite API.
**API Endpoints:**

+ Implement API endpoints for submitting feedback and retrieving aggregated feedback statistics.
**Dashboard:**

+ Develop a dynamic dashboard in NextJS to display summarized feedback for each repository.
+ Fetch and aggregate feedback data from the Appwrite collection.
**Data Visualization:**

+ Utilize DaisyUI components for data visualization, presenting feedback statistics using charts or graphs.
**User Notifications:**

+ Implement a notification system to inform repository owners of new feedback.
+ Include a link for repository owners to view detailed feedback on their repositories.
**Continuous Improvement:**

+ Regularly update the feedback system based on user feedback and evolving project requirements.

**Comment by eddiejaoude** [comment]
I think feedback is a good idea 👍 but will also require other features to support, for example like reporting, which will then need admin pages to manage these reported items. I will close for now as this is a big piece of work
