### ISSUE TITLE
[FEATURE] UI improvement - Login screen

### ISSUE THREAD

**Issue by subrat611** [EddieHubCommunity/RepoRater#64]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

## Description

Improve the visual appeal of the content by centering the `Login with GitHub` button.

![image](https://github.com/EddieHubCommunity/RepoRater/assets/77252075/a1d937f1-34f0-4c17-bf5f-014f7f5f0a7c)

### Proposed Solution

I want to align the content vertically instead of horizontally.

## Before
![image](https://github.com/EddieHubCommunity/RepoRater/assets/77252075/a1d937f1-34f0-4c17-bf5f-014f7f5f0a7c)

## After
![image](https://github.com/EddieHubCommunity/RepoRater/assets/77252075/cd68576d-342e-4266-9b79-212830ff125a)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

- Align the text to the center
- Setting up the width: 80% on screen (min-width: 1024px)

**Comment by eddiejaoude** [comment]
Thank you for the suggestion. The app is being redesigned at the moment, so I will this issue for now
