### ISSUE TITLE
[FEATURE] Docu Improvements: string size values & how to create API key

### ISSUE THREAD

**Issue by j-grosse** [EddieHubCommunity/RepoRater#70]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

## 1. add the values that Eddie gave me via discord in bullet points 4 and 5:

repos collection strings...
description: 1024
name: 128 (required)
owner: 128
logo: 512

ratings collection strings...
username: 128

## 2.  add to quickstart instructions under bullet point number 7. (in brackets):

Get you private keys from Appwrite (Overview > Integrations > "API Keys" tab > "+ Create API key" button) and add them to .env template (all data are required).

### Screenshots

![by default 2024-01-01 at 20 51 12](https://github.com/EddieHubCommunity/RepoRater/assets/103175813/67402c71-0bc7-4285-ac99-54a7cd7ef1c1)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

add text in Readme.md, see screenshot

**Comment by j-grosse** [comment]
I could also change the api example calls in the docs from eddiehub.org to eddiehub.io

**Comment by eddiejaoude** [comment]
Sorry for the delay, I have assigned it to you.



> I could also change the api example calls in the docs from eddiehub.org to eddiehub.io as they are not working: https://github.com/EddieHubCommunity/RepoRater?tab=readme-ov-file#github-action

Good spot, yes please 👍

**Comment by j-grosse** [comment]
> Sorry for the delay, I have assigned it to you.
> 
> > I could also change the api example calls in the docs from eddiehub.org to eddiehub.io as they are not working: https://github.com/EddieHubCommunity/RepoRater?tab=readme-ov-file#github-action
> 
> Good spot, yes please 👍

OK, I created a new issue for that: https://github.com/EddieHubCommunity/RepoRater/issues/79
