### ISSUE TITLE
[FEATURE] User Image

### ISSUE THREAD

**Issue by amanr-dev** [EddieHubCommunity/RepoRater#71]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

No

### Proposed Solution

Display the User's Profile picture after login.

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

By fetching user's image after login and display it :-)

**Comment by adityaoberai** [comment]
It might be tricky to represent user images without the presence of a profile section. Because without a profile, they don't add much value.

**Comment by eddiejaoude** [comment]
Thank you both for the collaboration 💪 

In the new version of the app, we have this feature - it is currently in testing in the Preview environment (so I will close this issue)

Here is a sneaky peak... 🤫 

<img width="374" alt="Screenshot 2024-01-03 at 12 02 48" src="https://github.com/EddieHubCommunity/RepoRater/assets/624760/c3a206b7-716f-4880-9977-918c60f235b3">

**Comment by amanr-dev** [comment]
> It might be tricky to represent user images without the presence of a profile section. Because without a profile, they don't add much value.



> Thank you both for the collaboration 💪
> 
> In the new version of the app, we have this feature - it is currently in testing in the Preview environment (so I will close this issue)
> 
> Here is a sneaky peak... 🤫
> 
> <img alt="Screenshot 2024-01-03 at 12 02 48" width="374" src="https://private-user-images.githubusercontent.com/624760/293908348-c3a206b7-716f-4880-9977-918c60f235b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyODY3NjMsIm5iZiI6MTcwNDI4NjQ2MywicGF0aCI6Ii82MjQ3NjAvMjkzOTA4MzQ4LWMzYTIwNmI3LTcxNmYtNDg4MC05OTc3LTkxOGM2MGYyMzViMy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDEwM1QxMjU0MjNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNjRkN2VlZDMxOWVlOWIzNzU0NGM2YWI0Y2JiOGZhYTVkNjViMzRiYzFmMjlmMDdhYmQ3N2ZjNjEyMGE0OGRjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.7LPFrH1sdyw3RwboVYu_461sZNKeonzWoH5JA2Y_kV4">
That looks awesome!👍

**Comment by eddiejaoude** [comment]
Thank you
