### ISSUE TITLE
[IMPROVEMENT] Margin below stats in home page

### ISSUE THREAD

**Issue by MadhuSaini22** [EddieHubCommunity/RepoRater#73]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

both

### Description

I think there's some need of margin at the bottom of stats card.

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

1. Go to https://repo-rater.eddiehub.io/ page.

### Screenshots

https://i.imgur.com/gnXNfTp.png

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Just add a margin at the stats container, like margin-bottom: 15px

**Comment by eddiejaoude** [comment]
Thank you for raising 👍 , we just deployed a redesign, I think this is now fix
