### ISSUE TITLE
[BUG] App logo should be link that redirect to home page

### ISSUE THREAD

**Issue by MadhuSaini22** [EddieHubCommunity/RepoRater#74]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

both

### Description

Header logo of the website should be a link that redirect to home page.

### Steps to Reproduce

If you know the steps, follow the below format and provide steps to reproduce

For example:

Go to https://repo-rater.eddiehub.io/popular page.
And click on icon on the header

### Screenshots

![image](https://github.com/EddieHubCommunity/RepoRater/assets/81684710/ec6c5dda-ba09-4325-99af-c852a1956601)

### Do you want to work on this issue?

No

**Comment by eddiejaoude** [comment]
Thank you for raising 👍
