### ISSUE TITLE
[FEATURE] Missing Dockerfile

### ISSUE THREAD

**Issue by Saurav-Pant** [EddieHubCommunity/RepoRater#80]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

There's no Dockerfile in the repo. Adding one would make it easier for people to use and deploy. 

### Proposed Solution

Simply create a Dockerfile in the main project folder. It helps users run the application smoothly in a container

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

https://github.com/Saurav-Pant/NoteWave/blob/main/Dockerfile

**Comment by eddiejaoude** [comment]
Thank you for raising, I don't think these needs a docker at the moment
