### ISSUE TITLE
[FEATURE] Add an Light mode

### ISSUE THREAD

**Issue by Vijaykv5** [EddieHubCommunity/RepoRater#82]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Add an light mode , so users can switch their theme according to their needs.

### Proposed Solution

Add a button for toggling between light &dark mode in navbar

### Do you want to work on this issue?

Yes

**Comment by eddiejaoude** [comment]
Thank you for raising, themes are not something we want to add at the moment
