### ISSUE TITLE
[BUG] No error for unauthenticated users

### ISSUE THREAD

**Issue by MuthoniMN** [EddieHubCommunity/RepoRater#84]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

Production

### Description

When an unauthenticated user tries to rate a repo, they are automatically redirected to the homepage. No errors are displayed or instructions to guide them that they should sign up first.

This can make it hard for new users navigating the platform

### Steps to Reproduce

1. Log out of Reporater or open in an incognito window
2. Go to the home page.
3. Try viewing or rating a repo

### Screenshots

![ezgif com-video-to-gif-converter](https://github.com/EddieHubCommunity/RepoRater/assets/105012834/7538aca5-48c3-423c-baf7-78322229161e)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

I would redirect the user to the login page instead. So that they can log in first leading to a better user experience.

**Comment by eddiejaoude** [comment]
Good spot, this was fixed earlier today shortly after the deployment

<img width="949" alt="Screenshot 2024-01-04 at 13 32 01" src="https://github.com/EddieHubCommunity/RepoRater/assets/624760/765281d4-799e-4dd3-b0b9-3c3345ffcf20">
