### ISSUE TITLE
[FEATURE] Add loading state spinner and lazy loading 

### ISSUE THREAD

**Issue by prime1999** [EddieHubCommunity/RepoRater#85]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

Just decided to improve user experience with a nice skeleton and spinner

### Proposed Solution

Add loading state to repos, stats, and activity sections and also prepare a spinner and skeleton component

### Screenshots

![04 01 2024_15 25 03_REC](https://github.com/EddieHubCommunity/RepoRater/assets/72664913/b4f72288-a3fe-4ef5-b870-8107f13d9ffa)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this

Add loading state to repos, stats, and activity sections and also prepare a spinner and skeleton component

**Comment by eddiejaoude** [comment]
> If "yes" to above, please explain how you would technically implement this

> Add loading state to repos, stats, and activity sections and also prepare a spinner and skeleton component

Please explain this again with a technical solution

**Comment by prime1999** [comment]
So the repos are been fetched from a backend but it will take some seconds or more for those with a bad network,
So the think is that I will create a loading state for the data that is been fetched, the stats, repos and the activities.
So if the data is still loading it will show the loader or a skeleton and also for the data that have been fetched but still yet to show on the website there will be a skeleton component for each parts.
I will extract each repo after mapping through them in the repos component and put each repo in a separate component called RepoList and call it in the repo component but they will have a fallback component to call the skeleton, something like this
![04 01 2024_20 30 31_REC](https://github.com/EddieHubCommunity/RepoRater/assets/72664913/53b52c97-d4be-4a34-948a-e2a3275d9291)
![04 01 2024_20 30 51_REC](https://github.com/EddieHubCommunity/RepoRater/assets/72664913/f46a49a2-df0c-48fb-a918-3ba490a6aeec)

**Comment by eddiejaoude** [comment]
NextJS has this built in, I think it would be better not to create our own but follow their documentation https://nextjs.org/docs/app/building-your-application/routing/loading-ui-and-streaming

**Comment by prime1999** [comment]
then I will update the code, let you know

**Comment by prime1999** [comment]
updated the code , I removed the spinner and used a skeleton instead so I used lazy loading as well,
https://nextjs.org/docs/app/building-your-application/optimizing/lazy-loading

**Comment by eddiejaoude** [comment]
ok I will take a look, where is the code?

**Comment by prime1999** [comment]
here 
![05 01 2024_11 33 27_REC](https://github.com/EddieHubCommunity/RepoRater/assets/72664913/949fc02e-3e3f-43da-a4e2-3200aa4c53c9)
![05 01 2024_11 32 31_REC](https://github.com/EddieHubCommunity/RepoRater/assets/72664913/2783fa0a-63d7-4b69-9de1-2fbdf1a60b8c)

**Comment by eddiejaoude** [comment]
You have now pushed a PR we can discuss there, no need for extra notification and confusion here
