### ISSUE TITLE
[BUG]  sidebar menu is not highlighted when clicked.

### ISSUE THREAD

**Issue by Nithishvb** [EddieHubCommunity/RepoRater#86]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production and dev environment 

### Description

Sidebar menu links are not highlighting upon clicking

### Steps to Reproduce

1. click the menu in the sidebar and it doesn't highlighted the clicked menu.

### Do you want to work on this issue?

Yes

**Comment by eddiejaoude** [comment]
Thank you for raising, this is a good idea, but you Sid you would like to work on it but did not fill in this part

> If "yes" to above, please explain how you would technically implement this

...?

**Comment by aqsaaqeel** [comment]
@eddiejaoude I would like to work on this if @Nithishvb is unavailable

**Comment by Hicode-dev** [comment]
@eddiejaoude  can i work on this ? can you please assign me to this ?

**Comment by eddiejaoude** [comment]
@aqsaaqeel I have not heard from the author who requested it, so I have assigned it to you

**Comment by eddiejaoude** [comment]
@Hicode-dev please read the message directly above yours, it was already requested

**Comment by aqsaaqeel** [comment]
> @Hicode-dev please read the message directly above yours, it was already requested - please look for another issue

Hey @eddiejaoude , the setup is taking me longer than expected. So if @Hicode-dev wants to take this one they can. I'll work on another as soon as my setup is complete

**Comment by eddiejaoude** [comment]
No problem, we need to improve the setup docs, let me know how we can help - come and chat to us on the EddieHub Discord, we can help more easily from there

**Comment by myj009** [comment]
Hi @eddiejaoude. I was able to set up the repo locally. Can you please assign this issue to me as @aqsaaqeel is not working on it?
