### ISSUE TITLE
[Trailing slash error] Unable to add a link with a trailing forward slash

### ISSUE THREAD

**Issue by sandramsc** [EddieHubCommunity/RepoRater#9]
### Description

**Current state**
Currently, if a repo link is pasted "GitHub Repo URL" input section and it ends with a **forward slash** the repo will be added but the page will not re-direct to the homepage with a success message. Instead a page with the error `SyntaxError: JSON.parse: unexpected end of data at line 1 column 1 of the JSON data` will persist.

i.e `https://github.com/EddieHubCommunity/BioDrop/`

**Desired state**

### Screenshots
![BE4](https://github.com/EddieHubCommunity/RepoRater/assets/19821445/55ad34b0-d15f-435a-ac5a-6940f12b6d8b)

![AFTRR](https://github.com/EddieHubCommunity/RepoRater/assets/19821445/411e391a-214f-4f2b-b78b-abe650c04218)

**Comment by eddiejaoude** [comment]
Thank you 👍  fixed in https://github.com/EddieHubCommunity/RepoRater/commit/bfb2fc807bf1393c747bed268816baac06afc0fa
