### ISSUE TITLE
[FEATURE] Improve website UI

### ISSUE THREAD

**Issue by Ronit-gurjar** [EddieHubCommunity/RepoRater#91]
### Is this a unique feature?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Is your feature request related to a problem/unavailable functionality? Please describe.

the new design looks great and really focused on user experience. the `Activity feed` feature is also great as it lets you know what other users are liking...but it will get bit annoying when the userbase increases, 
also i think that this section:-

![image](https://github.com/EddieHubCommunity/RepoRater/assets/92150685/f19983ec-aa7b-43ae-b85b-df7ccd10a48f)

could be placed in a better way rather that throwing it at the top ( or if there's a reason to put it there, pls let me know ). 
   

### for `Activity feed` problem :- 
The Component can be converted into a drop-down list style so that when ever the user wants to check they can simply pull it up rather than it being stuck there. 

### for `total counts and % section` problem :- 
they can be placed on the space we get from the activity component. they are still useful information as we get to know how many repos & user trust our ratings. (also they will be hidden by the activity component when it's pressed 'up', something like stacking above it.)

also the space freed from the `total counts and % section` can be utilized for a banner with meaningful text, and some actions like discussed in #16  

> [!IMPORTANT]  
> See the below screenshots for better understanding

### `Before : -`
![image](https://github.com/EddieHubCommunity/RepoRater/assets/92150685/c727f5e1-a6e8-4f5b-bb51-cbd3efb6a232)

 ### `After : - `
![Group 10](https://github.com/EddieHubCommunity/RepoRater/assets/92150685/b65fc709-23d6-486d-9300-dbfe1d4924d1)

### Do you want to work on this issue?

Yes

### If "yes" to above, please explain how you would technically implement this (issue will not be assigned if this is skipped)

implementing the discussed changes would be challenging but easy at the same time.
- i would just need to add some icon buttons in the `Activity component` and add some states for it to be 'up' or 'down'.
- I would need to take the `total counts and % section` and make it into a grid and some styling...basic frontend stuff.
- the banner...we can use the previous one or create a new one with a button for tutorial and information about readme badges or Docs maybe.

**Comment by eddiejaoude** [comment]
Thank you for raising a detailed issue. 

My thoughts...
- I do like the activity feed always being visible
- with the new stats there is a big wasted space under 
- I like the information at the top of the page, with the action buttons

**Comment by Ronit-gurjar** [comment]
the space left is actually were the activity feed will move up to , whenever clicked. let me know whether to work on the activity feed or not.
> Also Can i start working on the banner than?

**Comment by eddiejaoude** [comment]
I think step 1 should be to get the hero (information) on the web page first

**Comment by Ronit-gurjar** [comment]
Could you give me some details before I start working on the hero section...like
- heading
- description

And should we keep it as shown in the above design (similar to the old design) or you have any new ideas.
> I actually like the "impartial ratings" heading

**Comment by eddiejaoude** [comment]
You have it in your `after` screenshot - I think you got this text from the previous version of the website?

**Comment by Ronit-gurjar** [comment]
Yes ... okay, I'll start working

**Comment by eddiejaoude** [comment]
This issue has too much information in it, it is unclear what is being done. I will close this issue, please can you create a new issue with 1 specific change only. That can be assigned to you, and merged sooner once complete, rather than staying open for a long time and get conflicts etc.
