### ISSUE TITLE
[BUG] Overlaping info on repo list viewing on mobile 

### ISSUE THREAD

**Issue by eddiejaoude** [EddieHubCommunity/RepoRater#97]
### Has this bug been raised before?

- [X] I have checked "open" AND "closed" issues and this is not a duplicate

### Where did you find this bug?

production

### Description

When viewing repo list on mobile there is overlapping information. This information should be hidden for mobile 

### Steps to Reproduce

1. go to homepage https://repo-rater.eddiehub.io
2. on smaller screens information, especially for repos with longer names

### Screenshots

<img width="659" alt="Screenshot 2024-01-07 at 08 26 21" src="https://github.com/EddieHubCommunity/RepoRater/assets/624760/b46e14c1-d4b1-4115-827e-091f9aba06de">

### Do you want to work on this issue?

No

### If "yes" to above, please explain how you would technically implement this

Solution is to hide extra information when view on smaller / mobile screens

In file `src/components/Repos.js` on line `118` make the following changes...

```diff
- <p className="text-xs">
+ <p className="text-xs hidden sm:inline-block">
```

**Comment by professorabhay** [comment]
Hey, I would like to resolve this. 
Please assign it to me. 
So, it will be easy for others to understand that I'm working on it.
Needed Time to raise PR - 2hrs from assigning

**Comment by eddiejaoude** [comment]
Sure, I will assign it to you @professorabhay
